version: "2"
services:
  backend:
    build: ./backend
    depends_on: 
      - db
    links: 
        - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./frontend
    command: npm start 
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  
      

